FROM openjdk:11.0.10-jre-slim
LABEL maintainer=t2mc.net
ENV JAVA_OPTS -Xms128m -Xmx256m
ENV CONFIG_SERVICE_USER=$CONFIG_SERVICE_USER
ENV CONFIG_SERVICE_PASSWORD=$CONFIG_SERVICE_PASSWORD
ENV CONFIG_SERVICE_DOMAIN=$CONFIG_SERVICE_DOMAIN
ENV CONFIG_SERVICE_PORT=$CONFIG_SERVICE_PORT
ENV CONFIG_SERVER_PATH=$CONFIG_SERVER_PATH
ENV ACTIVE_PROFILE=$ACTIVE_PROFILE
ENV GIT_URI=$GIT_URI
ENV KEY_STORE_LOCATION=$KEY_STORE_LOCATION
ENV KEY_STORE_ALIAS=$KEY_STORE_ALIAS
ENV KEY_STORE_PASSWORD=$KEY_STORE_PASSWORD
ENV KEY_STORE_SECRET=$KEY_STORE_SECRET
ADD ./target/support-microservice.jar /app/app.jar
CMD ["/bin/bash", "-c", "exec java -server ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar"]
EXPOSE 8080

